version: '2'
services:
    fleet-app:
        image: fleet
        external_links:
            - fleet-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/fleet
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    fleet-postgresql:
        extends:
            file: postgresql.yml
            service: fleet-postgresql
